# Dev environment docker file
FROM node:18-alpine

RUN npm install -g pnpm

WORKDIR /app

# Copy dependencies
COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma/

# Install dependencies
RUN pnpm install

COPY . .

# Generate prisma types
RUN pnpm db:generate

EXPOSE 3000

# Startup command with hot reload
CMD ["pnpm", "dev:docker"]